version: "3.8"

# DATABASE_URI: mongodb://username:password@localhost:27017/planner
services:
  mongodb:
    image: bitnami/mongodb:8.0.10
    container_name: mongodb
    restart: no
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGODB_ROOT_USER: username
      MONGODB_ROOT_PASSWORD: password
      MONGODB_DATABASE: planner
    volumes:
      - mongo_data:/bitnami/mongodb
    networks:
      - data-tier

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: no
    ports:
      - "8081:8081" # Mongo Express web interface
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - data-tier

volumes:
  mongo_data:

networks:
  data-tier:
