version: "3.8"

services:
  mongodb:
    image: bitnami/mongodb:8.0.10
    container_name: mongodb
    restart: no
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_DATABASE: planner
    volumes:
      - mongo_data:/bitnami/mongodb
    networks:
      - data-tier

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: no
    ports:
      - "8081:8081" # Mongo Express web interface
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - data-tier

volumes:
  mongo_data:

networks:
  data-tier:
